language: python java
jdk:
  - openjdk6
python:
  - 2.7
install:
  - sudo apt-get install python-setuptools netcat
  - sudo easy_install distribute
  - python bootstrap.py -d
  - ./bin/buildout
  - java -jar parts/jettyrunner/jetty-runner-8.1.5.v20120716.jar src/xdocreport/REST-Service-Reporting-WebApplication/target/rest-service-reporting-*.war &
  - while ! nc -z localhost 8080; do sleep 1; done
script:
  - bin/test xdocreport_restclient
