language: python java
jdk:
  - openjdk6
python:
  - 2.7
install:
  - sudo apt-get install python-setuptools netcat
  - sudo easy_install distribute
  - python bootstrap.py -d
  - ./bin/buildout
  - java -jar parts/jettyrunner/jetty-runner-8.1.5.v20120716.jar --port 1300 src/xdocreport/REST-Service-Reporting-WebApplication/target/rest-service-reporting-*.war &
  - java -jar parts/jettyrunner/jetty-runner-8.1.5.v20120716.jar --port 1301 src/xdocreport/REST-Service-Converter-WebApplication/target/rest-service-converter-*.war &
  - while ! nc -z localhost 1300; do sleep 1; done
  - while ! nc -z localhost 1301; do sleep 1; done
script:
  - bin/test xdocreport_restclient
